/**
 * Cover template — separate file from interior per KDP spec
 * (front + spine + back combined, single PDF/X-1a).
 *
 * For MVP we ship only the interior PDF; the cover is generated by
 * Amazon's cover creator from the front-cover image we provide. This
 * file holds the front-cover render only.
 *
 * Atelier pass: bundled Zilla Slab display type (OFL, assets/fonts/) with
 * star cluster ornament and double gold frame, matching the Lulu lane.
 */
import { PDFDocument, StandardFonts, cmyk } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import fs from "node:fs";
import path from "node:path";

/** Convert sRGB (0..1 each) to a pdf-lib CMYK color object. */
function rgbToCmyk(r: number, g: number, b: number) {
  const k = 1 - Math.max(r, g, b);
  if (k === 1) return cmyk(0, 0, 0, 1);
  return cmyk((1 - r - k) / (1 - k), (1 - g - k) / (1 - k), (1 - b - k) / (1 - k), k);
}

export interface CoverInput {
  title: string;
  subtitle?: string;
  author: string;
  coverImageBytes?: Uint8Array;
  coverImageFormat?: "png" | "jpg";
}

const IN = 72;
const SIZE = (8.5 + 0.25) * IN; // 8.75 incl bleed

const PAPER = rgbToCmyk(1.0, 0.965, 0.898);
const PLUM = rgbToCmyk(0.29, 0.145, 0.27);
const GOLD = rgbToCmyk(0.831, 0.647, 0.455);

const STAR_PATH =
  "M 0 -10 C 1.5 -2.5, 2.5 -1.5, 10 0 C 2.5 1.5, 1.5 2.5, 0 10 " +
  "C -1.5 2.5, -2.5 1.5, -10 0 C -2.5 -1.5, -1.5 -2.5, 0 -10 Z";

export async function renderCoverPdf(input: CoverInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`${input.title} — cover`);
  pdf.setAuthor(input.author);
  pdf.setCreator("Inklings KDP cover-template (atelier)");
  pdf.registerFontkit(fontkit);

  const bundled = (() => {
    const dir = process.env.INK_FONT_DIR ?? path.join(process.cwd(), "assets", "fonts");
    try {
      return fs.readFileSync(path.join(dir, "ZillaSlab-Bold.ttf"));
    } catch {
      return null;
    }
  })();
  const display = bundled
    ? await pdf.embedFont(bundled, { subset: true })
    : await pdf.embedFont(StandardFonts.HelveticaBold);

  const page = pdf.addPage([SIZE, SIZE]);
  page.drawRectangle({ x: 0, y: 0, width: SIZE, height: SIZE, color: PAPER });

  // double gold frame
  const inset = 0.125 * IN + 15;
  page.drawRectangle({
    x: inset, y: inset, width: SIZE - 2 * inset, height: SIZE - 2 * inset,
    borderColor: GOLD, borderWidth: 1.6, borderOpacity: 0.85,
  });
  page.drawRectangle({
    x: inset + 6, y: inset + 6, width: SIZE - 2 * (inset + 6), height: SIZE - 2 * (inset + 6),
    borderColor: GOLD, borderWidth: 0.7, borderOpacity: 0.7,
  });

  // star cluster above the title
  const cx = SIZE / 2;
  const starY = SIZE - 1.55 * IN;
  page.drawSvgPath(STAR_PATH, { x: cx, y: starY, scale: 0.9, color: GOLD });
  page.drawSvgPath(STAR_PATH, { x: cx - 26, y: starY - 4, scale: 0.5, color: GOLD, opacity: 0.85 });
  page.drawSvgPath(STAR_PATH, { x: cx + 26, y: starY - 4, scale: 0.5, color: GOLD, opacity: 0.85 });

  if (input.coverImageBytes) {
    const img = input.coverImageFormat === "jpg"
      ? await pdf.embedJpg(input.coverImageBytes)
      : await pdf.embedPng(input.coverImageBytes);
    const margin = 0.45 * IN;
    const w = SIZE - 2 * margin;
    const h = SIZE - 2.6 * IN; // leave room for the title composition
    const ratio = Math.min(w / img.width, h / img.height);
    page.drawImage(img, {
      x: (SIZE - img.width * ratio) / 2,
      y: 0.55 * IN + (h - img.height * ratio) / 2,
      width: img.width * ratio, height: img.height * ratio,
    });
  }

  // centered display title
  const titleSize = 34;
  const tw = display.widthOfTextAtSize(input.title, titleSize);
  page.drawText(input.title, {
    x: (SIZE - tw) / 2, y: SIZE - 2.05 * IN,
    size: titleSize, font: display, color: PLUM,
  });
  return pdf.save();
}
