/**
 * Cover template — separate file from interior per KDP spec
 * (front + spine + back combined, single PDF/X-1a).
 *
 * For MVP we ship only the interior PDF; the cover is generated by
 * Amazon's cover creator from the front-cover image we provide. This
 * file holds the front-cover render only.
 */
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface CoverInput {
  title: string;
  subtitle?: string;
  author: string;
  coverImageBytes?: Uint8Array;
  coverImageFormat?: "png" | "jpg";
}

const IN = 72;
const SIZE = (8.5 + 0.25) * IN; // 8.75 incl bleed

export async function renderCoverPdf(input: CoverInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`${input.title} — cover`);
  pdf.setAuthor(input.author);
  pdf.setCreator("Inklings KDP cover-template");
  const page = pdf.addPage([SIZE, SIZE]);
  page.drawRectangle({ x: 0, y: 0, width: SIZE, height: SIZE, color: rgb(0.957, 0.918, 0.792) });

  if (input.coverImageBytes) {
    const img = input.coverImageFormat === "jpg"
      ? await pdf.embedJpg(input.coverImageBytes)
      : await pdf.embedPng(input.coverImageBytes);
    const margin = 0.25 * IN;
    const w = SIZE - 2 * margin;
    const ratio = Math.min(w / img.width, w / img.height);
    page.drawImage(img, {
      x: (SIZE - img.width * ratio) / 2,
      y: (SIZE - img.height * ratio) / 2,
      width: img.width * ratio, height: img.height * ratio,
    });
  }

  const font = await pdf.embedFont(StandardFonts.HelveticaBold);
  page.drawText(input.title, { x: 0.5 * IN, y: SIZE - 1.2 * IN, size: 42, font, color: rgb(0.29, 0.145, 0.27) });
  return pdf.save();
}
